import Head from 'next/head'
import Main from 'components/main'
import About from 'components/about'
import Projects from 'components/projects'
import Contact from 'components/Contact'

export default function Home({page}) {
  return (
    <main>
      <Head>
        <title>Ben Aiche Abdel Madjid | Trader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      {
        page === 'main' ?
        <Main />
        : page === 'projects' ?
        <Projects />
        : page === 'about' ?
        <About />
        : page === 'contact' ?
        <Contact />
        :
        404
      }
    </main>
  )
}
