import Head from 'next/head'
import Navbar from 'components/navbar'
import Main from 'components/main'
import About from 'components/about'
import Projects from 'components/projects'
import Contact from 'components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ben Aiche Abdel Madjid | Trader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* imported fonts*/}
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar />
      <Main />
      <Projects />
      <About />
      <Contact />
    </>
  )
}
